### ISSUE TITLE
 None type

### ISSUE THREAD

**Issue by kusanagi-tomoko** [soumikmohianuta/pixtoapp#1]
Hi, I used your project and met the following error, which might be a bug.
Traceback (most recent call last):
  File "test.py", line 163, in <module>
    generateProject(os.path.join(d,filename))
  File "test.py", line 109, in generateProject
    hierarchyProcessor.addTextToHierarchy(textInfo)
  File "/media/cheer/New Volume/Yuchen/pixtoapp/viewProcessor/HierarchyInfo.py", line 395, in addTextToHierarchy
    self.addTextToHierarchyInternal(self.hierarchyInfo.rootView, blocks)
  File "/media/cheer/New Volume/Yuchen/pixtoapp/viewProcessor/HierarchyInfo.py", line 441, in addTextToHierarchyInternal
    leafNodes = RectUtil.getLeafNodes(view)
  File "/media/cheer/New Volume/Yuchen/pixtoapp/RectUtils/RectUtil.py", line 715, in getLeafNodes
    getLeafNodesInternal(None, view, rectViews)
  File "/media/cheer/New Volume/Yuchen/pixtoapp/RectUtils/RectUtil.py", line 724, in getLeafNodesInternal
    getLeafNodesInternal(view, child, rectViews)
  File "/media/cheer/New Volume/Yuchen/pixtoapp/RectUtils/RectUtil.py", line 720, in getLeafNodesInternal
    if (parent != None and len(view.mChildren) == 0):
TypeError: object of type 'NoneType' has no len()

**Comment by soumikmohianuta** [comment]
Can you provide the image that you are trying? I can track and resolve the issue then. Sorry for late reply.
